gnn_saving_dir: 'models'
gnn_name: 'gcn'

param:
  bbbp:
    learning_rate1: 1e-4
    weight_decay1: 0
    learning_rate2: 0.01
    weight_decay2: 0
    milestones: None
    gamma: None
    batch_size: 32
    num_epochs: 100
    num_early_stop: 0
    gnn_latent_dim:
      - 128
      - 128
      - 128
    basis_dim: 32
    num_basis_per_class: 10
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    gnn_nonlinear: 'relu'
    readout: 'max'
    fc_latent_dim: []
    fc_dropout: 0.0
    fc_nonlinear: 'relu'
  MUTAG:
    learning_rate1: 1e-4
    weight_decay1: 0
    learning_rate2: 0.01
    weight_decay2: 0
    milestones: None
    gamma: None
    batch_size: 32
    num_epochs: 100
    num_early_stop: 0
    gnn_latent_dim:
      - 128
      - 128
      - 128
    basis_dim: 32
    num_basis_per_class: 10
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    gnn_nonlinear: 'relu'
    readout: 'max'
    fc_latent_dim: []
    fc_dropout: 0.0
    fc_nonlinear: 'relu'
  graph_sst2:
    learning_rate1: 1e-4
    weight_decay1: 0
    learning_rate2: 0.01
    weight_decay2: 0
    milestones: None
    gamma: None
    batch_size: 128
    num_epochs: 100
    num_early_stop: 0
    gnn_latent_dim:
      - 128
      - 128
      - 128
    basis_dim: 32
    num_basis_per_class: 10
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    gnn_nonlinear: 'relu'
    readout: 'max'
    fc_latent_dim: []
    fc_dropout: 0.0
    fc_nonlinear: 'relu'
  graph_sst5:
    learning_rate1: 1e-4
    weight_decay1: 0
    learning_rate2: 0.01
    weight_decay2: 0
    milestones: None
    gamma: None
    batch_size: 128
    num_epochs: 100
    num_early_stop: 0
    gnn_latent_dim:
      - 128
      - 128
      - 128
    basis_dim: 32
    num_basis_per_class: 10
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    gnn_nonlinear: 'relu'
    readout: 'max'
    fc_latent_dim: []
    fc_dropout: 0.0
    fc_nonlinear: 'relu'
  twitter:
    learning_rate1: 1e-4
    weight_decay1: 0
    learning_rate2: 0.01
    weight_decay2: 0
    milestones: None
    gamma: None
    batch_size: 128
    num_epochs: 500
    num_early_stop: 0
    gnn_latent_dim:
      - 128
      - 128
      - 128
    basis_dim: 32
    num_basis_per_class: 10
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    gnn_nonlinear: 'relu'
    readout: 'max'
    fc_latent_dim: []
    fc_dropout: 0.0
    fc_nonlinear: 'relu'
  ba_shapes:
    learning_rate1: 1e-2
    weight_decay1: 0
    learning_rate2: 0.01
    weight_decay2: 0
    milestones: None
    gamma: None
    batch_size: 1
    num_epochs: 2
    num_early_stop: 0
    gnn_latent_dim:
      - 128
      - 128
      - 128
    basis_dim: 128
    num_basis_per_class: 10
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: False
    gnn_emb_normalization: True
    graph_classification: False
    node_classification: True
    gnn_nonlinear: 'relu'
    readout: 'identity'
    fc_latent_dim: [ ]
    fc_dropout: 0.5
    fc_nonlinear: 'relu'
  ba_community:
    learning_rate1: 1e-2
    weight_decay1: 0
    learning_rate2: 0.01
    weight_decay2: 0
    milestones: None
    gamma: None
    batch_size: 1
    num_epochs: 2
    num_early_stop: 0
    gnn_latent_dim:
      - 128
      - 128
      - 128
    basis_dim: 128
    num_basis_per_class: 10
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: False
    gnn_emb_normalization: True
    graph_classification: False
    node_classification: True
    gnn_nonlinear: 'relu'
    readout: 'identity'
    fc_latent_dim: [ ]
    fc_dropout: 0.5
    fc_nonlinear: 'relu'
  pubmed:
    learning_rate1: 1e-4
    weight_decay1: 0
    learning_rate2: 0.01
    weight_decay2: 0
    milestones: None
    gamma: None
    batch_size: 1
    num_epochs: 5
    num_early_stop: 0
    gnn_latent_dim:
      - 1024
      - 1024
      - 1024
    basis_dim: 128
    num_basis_per_class: 10
    gnn_dropout: 0.5
    add_self_loop: True
    gcn_adj_normalization: True
    gnn_emb_normalization: False
    graph_classification: False
    node_classification: True
    gnn_nonlinear: 'relu'
    readout: 'identity'
    fc_latent_dim: [ ]
    fc_dropout: 0.5
    fc_nonlinear: 'relu'
  cora:
    learning_rate1: 1e-4
    weight_decay1: 0
    learning_rate2: 0.01
    weight_decay2: 0
    milestones: None
    gamma: None
    batch_size: 1
    num_epochs: 5
    num_early_stop: 0
    gnn_latent_dim:
      - 1024
      - 1024
      - 1024
    basis_dim: 128
    num_basis_per_class: 10
    gnn_dropout: 0.5
    add_self_loop: True
    gcn_adj_normalization: True
    gnn_emb_normalization: False
    graph_classification: False
    node_classification: True
    gnn_nonlinear: 'relu'
    readout: 'identity'
    fc_latent_dim: [ ]
    fc_dropout: 0.5
    fc_nonlinear: 'relu'
  citeseer:
    learning_rate1: 1e-4
    weight_decay1: 0
    learning_rate2: 0.01
    weight_decay2: 0
    milestones: None
    gamma: None
    batch_size: 1
    num_epochs: 5
    num_early_stop: 0
    gnn_latent_dim:
      - 1024
      - 1024
      - 1024
    basis_dim: 128
    num_basis_per_class: 10
    gnn_dropout: 0.5
    add_self_loop: True
    gcn_adj_normalization: True
    gnn_emb_normalization: False
    graph_classification: False
    node_classification: True
    gnn_nonlinear: 'relu'
    readout: 'identity'
    fc_latent_dim: [ ]
    fc_dropout: 0.5
    fc_nonlinear: 'relu'
  tree_grid:
    learning_rate1: 1e-4
    weight_decay1: 0
    learning_rate2: 0.01
    weight_decay2: 0
    milestones: None
    gamma: None
    batch_size: 1
    num_epochs: 100
    num_early_stop: 0
    gnn_latent_dim:
      - 128
      - 128
      - 128
    basis_dim: 128
    num_basis_per_class: 10
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: False
    gnn_emb_normalization: True
    graph_classification: False
    node_classification: True
    gnn_nonlinear: 'relu'
    readout: 'identity'
    fc_latent_dim: [ ]
    fc_dropout: 0.5
    fc_nonlinear: 'relu'
  tree_cycle:
    learning_rate1: 1e-4
    weight_decay1: 0.0
    learning_rate2: 0.01
    weight_decay2: 0.0
    milestones: None
    gamma: None
    batch_size: 1
    num_epochs: 100
    num_early_stop: 0
    gnn_latent_dim:
      - 20
      - 20
      - 20
    basis_dim: 32
    num_basis_per_class: 10
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: False
    gnn_emb_normalization: True
    graph_classification: False
    node_classification: True
    gnn_nonlinear: 'relu'
    readout: 'identity'
    fc_latent_dim: [ ]
    fc_dropout: 0.0
    fc_nonlinear: 'relu'
  ba_2motifs:
    learning_rate1: 1e-4
    weight_decay1: 0.0
    learning_rate2: 0.01
    weight_decay2: 0.0
    milestones: None
    gamma: None
    batch_size: 32
    num_epochs: 100
    num_early_stop: 0
    gnn_latent_dim:
      - 20
      - 20
      - 20
    basis_dim: 32
    num_basis_per_class: 10
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: False
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    gnn_nonlinear: 'relu'
    readout: 'mean'
    fc_latent_dim: []
    fc_dropout: 0.0
    fc_nonlinear: 'relu'
  bace:
    learning_rate1: 1e-4
    weight_decay1: 0.0
    learning_rate2: 0.01
    weight_decay2: 0.0
    milestones: None
    gamma: None
    batch_size: 64
    num_epochs: 100
    num_early_stop: 0
    gnn_latent_dim:
      - 128
      - 128
      - 128
    basis_dim: 32
    num_basis_per_class: 10
    gnn_dropout: 0.0
    add_self_loop: True
    gcn_adj_normalization: True
    gnn_emb_normalization: False
    graph_classification: True
    node_classification: False
    gnn_nonlinear: 'relu'
    readout: 'max'
    fc_latent_dim: [ ]
    fc_dropout: 0.0
    fc_nonlinear: 'relu'